// <auto-generated />
namespace HandIn3._2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hey3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hey3));
        
        string IMigrationMetadata.Id
        {
            get { return "201804230919553_hey3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
